#!/usr/bin/env node

import fs from 'fs';
import { IOSBuildMetadata } from '../../utils/types';
import { getErrorLogFile } from '../../utils/config';
import { installApp, launchApp } from './helper';

const METADATA_PATH = process.argv[2];
const simulatorId = process.argv[3];

if (!METADATA_PATH) {
  console.error('Usage: ./run-ios-tests.js <METADATA_JSON_FILE> [SIMULATOR_ID]');
  console.error('  METADATA_JSON_FILE: Path to the metadata JSON file generated by build-ios-app.js');
  console.error('  SIMULATOR_ID: iOS simulator UDID (optional)');
  process.exit(1);
}

interface InstallResult {
  bundleId: string;
  version: string;
  architecture: 'old' | 'new';
  simulatorId: string;
}

function installAndLaunchApp(): InstallResult {
  console.log('\n=== Installing and Launching iOS App ===\n');

  console.log('Reading metadata file...');
  const metadata = JSON.parse(fs.readFileSync(METADATA_PATH, 'utf8')) as IOSBuildMetadata;

  const bundleId = metadata.bundleId;
  const version = metadata.version;
  const appPath = metadata.appPath;
  const architecture = metadata.architecture;
  const ERROR_LOG_FILE = getErrorLogFile();

  console.log(`Bundle ID: ${bundleId}`);
  console.log(`Version: ${version}`);
  console.log(`Architecture: ${architecture}`);
  console.log(`App path: ${appPath}`);

  if (!fs.existsSync(appPath)) {
    throw new Error(`App not found at ${appPath}`);
  }

  if (!simulatorId) {
    throw new Error('No simulator ID provided');
  }

  console.log(`Using simulator: ${simulatorId}`);

  installApp(simulatorId, appPath, ERROR_LOG_FILE);
  launchApp(simulatorId, bundleId, ERROR_LOG_FILE);

  fs.writeFileSync(METADATA_PATH, JSON.stringify(metadata, null, 2));

  console.log('\n=== App Installation and Launch Completed ===\n');

  return { bundleId, version, architecture, simulatorId };
}

installAndLaunchApp(); 